[package]
name = "glx"
version = "0.0.1"
license = "Apache-2.0"
authors = []
build = "build.rs"
documentation = "http://doc.servo.org/glx/"

[build-dependencies]
gl_generator = "*"
khronos_api = "*"

[dependencies]
gl_common = "*"
libc = "*"
