[package]
name = "glx"
version = "0.0.1"
authors = []
build = "build.rs"

[build-dependencies.gl_generator]
git = "https://github.com/bjz/gl-rs.git"

[dependencies.gl_common]
git = "https://github.com/bjz/gl-rs"